vhbb/cmssw

VHbbAnalysis/Heppy/test/vhbb.py
Factorized, cleaned PR #8 - VHbb only.
=> ttH variables (lhe Nb/c/l/g, PDF x, id, q, t->W->l leptons, VHbb)

VHbbAnalysis/Heppy/test/vhbb.py
=> added gen b from top for tth

VHbbAnalysis/Heppy/test/vhbb.py
Uses the modified[1] GeneratorAnalyzer to save generated neutrinos form top quarks.
[1] https://github.com/cbernet/cmssw/pull/26
=> Heppy gennufromtop

DataFormats/JetReco/interface/HTTTopJetTagInfo.h, DataFormats/JetReco/src/classes_4.h, DataFormats/JetReco/src/classes_def_4.xml, RecoJets/JetAlgorithms/interface/HEPTopTaggerV2.h, RecoJets/JetAlgorithms/interface/HEPTopTaggerWrapperV2.h, RecoJets/JetAlgorithms/src/HEPTopTaggerV2.cc, RecoJets/JetAlgorithms/src/HEPTopTaggerWrapperV2.cc, RecoJets/JetProducers/plugins/HTTTopJetProducer.cc, RecoJets/JetProducers/plugins/HTTTopJetProducer.h, RecoJets/JetProducers/plugins/VirtualJetProducer.cc, RecoJets/JetProducers/plugins/VirtualJetProducer.h, VHbbAnalysis/Heppy/python/AdditionalBoost.py, VHbbAnalysis/Heppy/python/vhbbobj.py, VHbbAnalysis/Heppy/test/combined_cmssw.py, VHbbAnalysis/Heppy/test/vhbb-combined.py
HEPTopTagger for Heppy.
Updated branches, added subjet information.
@arizzi
=> Dev httv2 heppy74x

VHbbAnalysis/Heppy/python/vhbbobj.py, VHbbAnalysis/Heppy/test/vhbb-combined.py, VHbbAnalysis/Heppy/test/vhbb.py
I made a new branch named 74X starting from
- yesterday's version of PR #67 
- cbernet/#41
- CMSSW 745
=> Replace PR #67 on 74X branch

PhysicsTools/Heppy/python/analyzers/objects/JetAnalyzer.py, VHbbAnalysis/Heppy/python/VHbbAnalyzer.py, VHbbAnalysis/Heppy/python/vhbbobj.py, VHbbAnalysis/Heppy/src/FastSoftActivity.cc, VHbbAnalysis/Heppy/test/crab/heppy_crab_script.sh
This fixes:
- the default btag used in sorting of jets
- the indices of jets 
- the crab scripts
=> Several fixes

PhysicsTools/Heppy/python/analyzers/objects/JetAnalyzer.py, VHbbAnalysis/Heppy/test/crab/heppy_crab_script.sh
=> fix crab script and change neutrino matching to genjets

VHbbAnalysis/Heppy/test/vhbb.py
This PR adds in the ntuples a variable for each trigger bit (instead of the OR of multiple triggers).
=> Unroll trigger bits

PhysicsTools/Heppy/python/analyzers/core/TriggerBitAnalyzer.py
this is a trivial fix, please just merge it
this closes #103
=> Fix trigger bits unrolling

VHbbAnalysis/Heppy/python/VHbbAnalyzer.py, VHbbAnalysis/Heppy/test/vhbb.py
=> adding code to find ISR jet in VH events

PhysicsTools/Heppy/python/analyzers/objects/METAnalyzer.py, VHbbAnalysis/Heppy/test/crab/heppy_crab_script.sh, VHbbAnalysis/Heppy/test/vhbb.py
- speed up tkMET see cbernet/#46
- more log in crab to debug crashes
=> More v12fixes speed up

PhysicsTools/Heppy/python/analyzers/objects/JetAnalyzer.py
importing cbernet/cmssw#43
@jpata
=> Heppy 7 4 5 jetpfcleaning

PhysicsTools/Heppy/python/analyzers/objects/JetAnalyzer.py, VHbbAnalysis/Heppy/python/VHbbAnalyzer.py, VHbbAnalysis/Heppy/python/vhbbobj.py, VHbbAnalysis/Heppy/test/vhbb.py
=> Overlapjet index

VHbbAnalysis/Heppy/python/VHbbAnalyzer.py
=> raise pt thrshold for VH SA 

PhysicsTools/Heppy/python/physicsutils/BTagWeightCalculator.py
#122  @degrutto 
import from cbernet PR
=> Heppy7 4 5 fix btag weights mdg

VHbbAnalysis/Heppy/test/vhbb.py
This PR add metPuppi_phi.
What about to add directly metPuppi as globalObjects?
=> adding metPuppi_phi

PhysicsTools/Heppy/python/analyzers/objects/LeptonAnalyzer.py
Cherry picked Spring15 ele eff areas from CMG.
Solves https://github.com/vhbb/cmssw/issues/175
**Test ongoing, don't merge yet!**
=> from CERN-PH-CMG/cmg-cmssw/pull/501: implement the Spring15 Effective Areas for 25ns and 50ns

VHbbAnalysis/Heppy/python/VBFblikelihood.py, VHbbAnalysis/Heppy/python/VHbbAnalyzer.py, VHbbAnalysis/Heppy/python/vhbbobj.py, VHbbAnalysis/Heppy/test/TMVA_blikelihood_vbf_singlebtag_v13_id.xml, VHbbAnalysis/Heppy/test/crab/heppy_crab_config.py, VHbbAnalysis/Heppy/test/vhbb.py
VBF blikelihood with only 3 commits.
=>  VBF blikelihood

VHbbAnalysis/Heppy/python/VHGeneratorAnalyzer.py, VHbbAnalysis/Heppy/python/vhbbobj.py, VHbbAnalysis/Heppy/test/vhbb.py
infine uscimmo a rivedere le stelle
=> Vhbb heppy76 x add lhe weights

VHbbAnalysis/Heppy/python/vhbbobj.py, VHbbAnalysis/Heppy/test/vhbb.py
Now we have HFStats1,HFStats2,LFStats1, LFStats2
=> added decorrelated Stats uncert for HF and LF

VHbbAnalysis/Heppy/python/TriggerTable.py
HLT menu was change between 74x and 76x, this update in path names reflects changes in the HLT menu.
=> Update ttH hadronic HLT path names

VHbbAnalysis/Heppy/python/VHbbAnalyzer.py
=> allow events with nJets=1 but Pt>200

VHbbAnalysis/Heppy/test/vhbb.py
=> Revert "use "triggerTableData" in 76X MC"

VHbbAnalysis/Heppy/test/vhbb_combined_data.py, VHbbAnalysis/Heppy/test/vhbb_data.py
=> Forgot one commit on #302

VHbbAnalysis/Heppy/python/VHbbAnalyzer.py, VHbbAnalysis/Heppy/test/vhbb.py
#301 
#299 
#298 
@silviodonato
=> Add more Rho variables, remove metNoPU, add BX number

VHbbAnalysis/Heppy/src/ColorFlow.cc
Fixing missing assignement #241
=> Fixing missing assignment

PhysicsTools/Heppy/python/analyzers/core/TriggerObjectsAnalyzer.py, VHbbAnalysis/Heppy/test/vhbb.py, VHbbAnalysis/Heppy/test/vhbb_data.py
reverting InputTag change RECO/PAT in trigger
=> reverting InputTag change RECO/PAT in trigger

VHbbAnalysis/Heppy/python/TriggerObjectsList.py
adding hltPFHT in trigger objects
=> adding hltPFHT in trigger objects

VHbbAnalysis/Heppy/python/VHGeneratorAnalyzer.py, VHbbAnalysis/Heppy/python/VHbbAnalyzer.py
=> fixed bug causing crash in pdf

VHbbAnalysis/Heppy/python/JetRegression.py, VHbbAnalysis/Heppy/test/ttbar-spring15.weights.xml, VHbbAnalysis/Heppy/test/vhbb.py
=> take @cvernier stuff

VHbbAnalysis/Heppy/python/TriggerObjectsList.py, VHbbAnalysis/Heppy/python/vhbbobj.py, VHbbAnalysis/Heppy/test/vhbb.py
This PR adds the HLT electrons, muons and L1 MHT and HT to the trigger object collection saved in the ntuples.
@degrutto @bianchini
=> Update on the trigger objects

PhysicsTools/Heppy/python/analyzers/core/TriggerObjectsAnalyzer.py, VHbbAnalysis/Heppy/python/TriggerObjectsList.py, VHbbAnalysis/Heppy/python/vhbbobj.py, VHbbAnalysis/Heppy/test/vhbb.py
Speed-up  the trigger object code
+ remove the L1 HT object (it doesn't work)
=> Speed-up  trigger object code

VHbbAnalysis/Heppy/python/JetRegression.py, VHbbAnalysis/Heppy/test/crab/heppy_crab_config.py, VHbbAnalysis/Heppy/test/crab/heppy_crab_config_env.py, VHbbAnalysis/Heppy/test/crab_data/heppy_crab_config.py
=> fix jer=0 and limit task name len

PhysicsTools/Heppy/python/analyzers/core/PileUpAnalyzer.py
=> Fix of PU weight down bug

VHbbAnalysis/Heppy/python/btagSF.py
Fixed a bug which was making SF=0 in btagSF
=> Vhbb heppy76 x new b tag

VHbbAnalysis/Heppy/test/crab/datasets_MCRUN2_25ns_RunIIFall15MiniAODv2-PU25nsData2015v1_76X.txt
=> add DYJetsToLL sample

VHbbAnalysis/Heppy/test/TMVA_blikelihood_vbf_cmssw76_h21trained.weights.xml, VHbbAnalysis/Heppy/test/crab/heppy_crab_config.py, VHbbAnalysis/Heppy/test/vhbb.py
VBF blikelihood new weights, trained using h21b with cmssw76 and new jet energy scale
=> VBF blikelihood new weights, trained using h21b with cmssw76 and new jet energy scale

VHbbAnalysis/Heppy/test/vhbb.py
=> Lb before v21
